// Dialog for Scene 3
export const scene3Dialog = [
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    text: 'Akhirnya lokasi dimana 3 titik data itu berhasil diselamatkan.',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    text: '',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    text: 'E.V.I: Heii... Boleh kah aku bertanya sesuatu?',
    effect: null,
    characterImage: '/assets/game/scene3/evi3.png',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    text: 'E.V.I ingin tahu pendapatmu terkait inovasi survei yang dilengkapi permainan ini?',
    effect: null,
    characterImage: '/assets/game/scene3/evi3.png',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    effect: null,
    characterImage: '/assets/game/scene3/evi4.png',
    questionId: 12,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    effect: null,
    characterImage: '/assets/game/scene3/evi4.png',
    questionId: 13,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    effect: null,
    characterImage: '/assets/game/scene3/evi4.png',
    questionId: 14,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    effect: null,
    characterImage: '/assets/game/scene3/evi4.png',
    questionId: 15,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene3/frame2.gif',
    audio: '/assets/game/scene3/audio3.flac',
    text: 'VIRUS: (Transisi tiba-tiba, layar berkedip merah)',
    effect: 'neon',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    text: 'Gameplay: Top-down shooter. Kalahkan boss virus.',
    effect: null,
    questionId: null,
    autoPlay: true,
    isSubmit: true,
  },
]; 