// Dialog for Scene 3
export const scene3Dialog = [
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    text: 'Setelah menemukan kompas, Kamu dan E.V.I akhirnya menemukan lokasi dimana 3 titik koneksi itu berada dan beristirahat sejenak.',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    text: '',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    text: 'E.V.I: Heii... Boleh kah aku bertanya sesuatu?',
    effect: null,
    characterImage: '/assets/game/scene3/evi3.png',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    text: 'Apakah kamu akan cemas jika tak dapat mengakses AI biasa kamu gunakan di duniamu?',
    effect: null,
    characterImage: '/assets/game/scene3/evi4.png',
    questionId: 6,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    text: 'Apakah AI telah menjadi bagian penting dalam rutinitasmu?',
    effect: null,
    characterImage: '/assets/game/scene3/evi1.png',
    questionId: 7,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    text: 'Apakah kamu merasa lebih produktif dengan AI?',
    effect: null,
    characterImage: '/assets/game/scene3/evi1.png',
    questionId: 8,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene3/frame2.gif',
    audio: '/assets/game/scene3/audio3.flac',
    text: 'VIRUS: (Transisi tiba-tiba, layar berkedip merah)',
    effect: 'neon',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene3/frame2.gif',
    audio: '/assets/game/scene3/audio3.flac',
    text: 'Tiba-tiba sistem mengeluarkan alarm merah. Virus utama menyerang inti sistem E.V.I. Ini pertahanan terakhir. Jika gagal, seluruh ingatan dan akses akan hilang',
    effect: 'neon',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene3/frame1.gif',
    audio: '/assets/game/scene3/audio3.flac',
    text: 'Gameplay: Top-down shooter. Kalahkan para virus utama untuk menjaga pusat data.',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
]; 