// Dialog for Scene 2
export const scene2Dialog = [
  {
    image: '/assets/game/scene2/frame1.png',
    audio: '/assets/game/scene2/audio2.mp3',
    text: 'Scene 2: Pusat data E.V.I telah aman. E.V.I mengaktualisasikan dirinya sebagai karakter.',
    effect: null,
    characterImage: '/assets/game/scene1/character1.png', // to show character image in certain frame.
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.mp3',
    text: 'Pusat data E.V.I telah aman. E.V.I mengaktualisasikan dirinya juga sebagai seorang karakter.',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene2/char.gif',
    audio: '/assets/game/scene2/audio2.mp3',
    text: 'E.V.I: Sebelum data aman, proses lanjutan. Apa tujuan utama kamu menggunakan AI?',
    effect: null,
    questionId: 3,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/char.gif',
    audio: '/assets/game/scene2/audio2.mp3',
    text: 'E.V.I: Jenis AI yang paling sering kamu gunakan?',
    effect: null,
    questionId: 4,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/char.gif',
    audio: '/assets/game/scene2/audio2.mp3',
    text: 'E.V.I: Wah, aku dan keturunan AI seperti itu juga banyak yang menggunakan!',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene2/char2.gif',
    audio: '/assets/game/scene2/audio2.mp3',
    text: 'E.V.I: Sekarang, seberapa setuju kamu menggunakan AI di pekerjaan sehari-hari?',
    effect: null,
    questionId: 5,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/char.gif',
    audio: '/assets/game/scene2/audio2.mp3',
    text: 'E.V.I: Terima kasih! Data kamu sudah terekam.',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene2/virus.gif',
    audio: '/assets/game/scene2/audio2.mp3',
    text: 'VIRUS: (Transisi tiba-tiba, layar berkedip merah)',
    effect: 'neon',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene2/frame3.png',
    audio: '/assets/game/scene2/audio2.mp3',
    text: 'Virus level 2 menyerang jalur jaringan antar modul AI. Kamu harus mengawasi dan mempertahankan 3 titik koneksi sebelum rusak total.',
    effect: null,
    questionId: null,
    autoPlay: true,
    redirectToTowerGames: true,
    waves: 2,
  },
]; 