// Dialog for Scene 4
export const scene4Dialog = [
  {
    image: '/assets/game/scene4/frame1.png',
    audio: '/assets/game/scene4/audio4.flac',
    text: 'Akhirnya, sistem berhasil dipulihkan dan E.V.I kembali normal.',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene4/frame1.png',
    audio: '/assets/game/scene4/audio4.flac',
    text: '',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene4/frame2.gif',
    audio: '/assets/game/scene4/audio4.flac',
    text: 'Virus Utama: AAAAARRRRGHHH!!!(Meninggoy)',
    effect: null,
    characterImage: '/assets/game/scene1/boss.png',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene4/frame2.gif',
    audio: '/assets/game/scene4/audio4.flac',
    text: 'E.V.I: Terima kasih atas bantuanmu selama ini!',
    effect: null,
    characterImage: '/assets/game/scene1/evi2.png',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene4/frame2.gif',
    audio: '/assets/game/scene4/audio4.flac',
    text: 'E.V.I: Apakah kamu biasanya sering mengandalkan AI untuk membuat segala keputusan?',
    effect: null,
    characterImage: '/assets/game/scene1/evi4.png',
    questionId: 9,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene4/frame2.gif',
    audio: '/assets/game/scene4/audio4.flac',
    text: 'Menurutmu, apakah AI bisa memberi solusi yang lebih baik dari manusia?',
    effect: null,
    characterImage: '/assets/game/scene1/evi1.png',
    questionId: 10,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene4/frame3.png',
    audio: '/assets/game/scene4/audio4.flac',
    text: 'E.V.I: Kamu sudah menjawab semua pertanyaanku. Aku.. mulai memahami manusia lebih baik.',
    effect: null,
    characterImage: '/assets/game/scene1/evi2.png',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene4/frame3.png',
    audio: '/assets/game/scene4/audio4.flac',
    text: 'Terima kasih telah bermain! Sampai jumpa di petualangan berikutnya.',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
]; 