// Dialog for Scene 3
export const scene3Dialog = [
  {
    image: '/assets/game/scene3/frame1.png',
    audio: '/assets/game/scene3/audio3.mp3',
    text: 'Setelah menemukan kompas, Kamu dan E.V.I akhirnya menemukan lokasi dimana 3 titik koneksi itu berada dan beristirahat sejenak.',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene3/retro.gif',
    audio: '/assets/game/scene3/audio3.mp3',
    text: '',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene3/char.gif',
    audio: '/assets/game/scene3/audio3.mp3',
    text: 'E.V.I: Tidak, aku lagi istirahat sebentar...',
    effect: null,
    questionId: null,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene3/char.gif',
    audio: '/assets/game/scene3/audio3.mp3',
    text: 'Saya merasa cemas jika tidak dapat mengakses AI yang biasa saya gunakan',
    effect: null,
    questionId: 6,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene3/char.gif',
    audio: '/assets/game/scene3/audio3.mp3',
    text: 'Saya merasa AI telah menjadi bagian penting dalam rutinitas saya',
    effect: null,
    questionId: 7,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene3/char.gif',
    audio: '/assets/game/scene3/audio3.mp3',
    text: 'Saya merasa lebih produktif saat menggunakan AI',
    effect: null,
    questionId: 8,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene3/frame2.png',
    audio: '/assets/game/scene3/audio3.mp3',
    text: 'Gameplay: Top-down shooter. Kalahkan para virus utama untuk menjaga pusat data.',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
]; 