// Sebelum scene1Dialog dijalankan, pastikan user sudah mengisi nama dan lokasi di UI
export const scene1Dialog = [
  {
    image: '/assets/game/scene1/frame3.png',
    audio: '/assets/game/scene1/audio1.flac',
    text: 'Haloooooo…',
    effect: 'blink-shake',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    text: 'Perkenalkan namaku E.V.I, pemandu dalam pengisian kuesioner di sini.',
    effect: 'blink-shake',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    text: 'EVI: Sebelum kamu mengisi kuesionernya, E.V.I ingin tahu identitasmu.',
    effect: 'blink-shake',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    questionId: 1,
    effect: 'blink-shake',
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    text: 'EVI: Terima kasih atas informasinya.',
    effect: 'blink-shake',
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    text: 'EVI: Sekarang, E.V.I ingin tahu intensitasmu dalam mengisi kuesioner.',
    effect: 'blink-shake',
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    effect: 'blink-shake',
    questionId: 2, 
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    effect: 'blink-shake',
    questionId: 3, 
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    effect: 'blink-shake',
    questionId: 4, 
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame3.png',
    audio: '/assets/game/scene1/audio1.flac',
    text: 'EVI: Terima kasih atas informasinya. Sebagai hadiah selamat bermain game tower defense level 1 berikut ini',
    effect: 'blink-shake',
    questionId: null,
    autoPlay: true,
  },
 ]; 