// Sebelum scene1Dialog dijalankan, pastikan user sudah mengisi nama dan lokasi di UI
export const scene1Dialog = [
  {
    image: '/assets/game/scene1/frame1.png',
    audio: '/assets/game/scene1/audio1.flac',
    text: '(berjalan pelan, melihat terminal tua berdebu)',
    effect: null,
    questionId: null,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    text: 'Komputer ini tiba-tiba menyala sendiri...',
    questionId: null,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame3.png',
    audio: '/assets/game/scene1/audio1.flac',
    text: 'Haloooooo…',
    effect: 'blink-shake',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    text: 'Perkenalkan namaku E.V.I, pemandu dalam pengisian kuesioner di sini.',
    effect: 'blink-shake',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    text: 'E.V.I.: Sebelum kamu mengisi kuesionernya, E.V.I ingin tahu identitasmu.',
    effect: 'blink-shake',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    questionId: 1,
    effect: 'blink-shake',
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    text: 'E.V.I.: Terima kasih atas informasinya.',
    effect: 'blink-shake',
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    text: 'E.V.I.: Sekarang, E.V.I ingin tahu intensitasmu dalam mengisi kuesioner.',
    effect: 'blink-shake',
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    effect: 'blink-shake',
    questionId: 2, 
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    effect: 'blink-shake',
    questionId: 3, 
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.flac',
    effect: 'blink-shake',
    questionId: 4, 
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/berguncang1.gif',
    audio: '/assets/game/scene1/audio1.flac',
    text: 'Komputer mulai bergetar hebat...',
    effect: 'shake',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene1/berguncang2.gif',
    audio: '/assets/game/scene1/audio1.flac',
    text: 'VIRUS muncul di layar!',
    effect: 'neon',
    questionId: null,
    autoPlay: true,
    redirectToTowerGames: true,
    waves: 1,
  }
 ]; 