// Dialog for Scene 2
export const scene2Dialog = [
  {
    image: '/assets/game/scene2/frame1.png',
    audio: '/assets/game/scene2/audio2.flac',
    text: 'Sebelum lanjut ke permainan level berikutnya, EVI ingin tahu perasaanmu ketika diminta untuk mengisi kuesioner',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.flac',
    effect: null,
    characterImage: '/assets/game/scene2/evi1.png',
    questionId: 5,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.flac',
    effect: null,
    characterImage: '/assets/game/scene2/evi1.png',
    questionId: 6,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.flac',
    effect: null,
    characterImage: '/assets/game/scene2/evi1.png',
    questionId: 7,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.flac',
    effect: null,
    characterImage: '/assets/game/scene2/evi1.png',
    questionId: 8,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.flac',
    effect: null,
    characterImage: '/assets/game/scene2/evi1.png',
    questionId: 9,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.flac',
    effect: null,
    characterImage: '/assets/game/scene2/evi1.png',
    questionId: 10,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.flac',
    effect: null,
    characterImage: '/assets/game/scene2/evi1.png',
    questionId: 11,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/frame3.gif',
    audio: '/assets/game/scene2/audio2.flac',
    text: 'Oke, jawabanmu sudah E.V.I simpan, sekarang kamu bisa lanjut ke permainan level 2, selamat bermain!',
    effect: null,
    questionId: null,
    autoPlay: true,
    redirectToTowerGames: true,
    waves: 2,
  },
]; 