// Dialog for Scene 2
export const scene2Dialog = [
  {
    image: '/assets/game/scene2/frame1.png',
    audio: '/assets/game/scene2/audio2.flac',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene2/frame1.png',
    audio: '/assets/game/scene2/audio2.flac',
    text: 'Pusat data E.V.I telah aman. E.V.I mengvisualisasikan dirinya juga sebagai seorang karakter.',
    effect: null,
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.flac',
    text: 'E.V.I: Sebagian data aman.',
    effect: null,
    characterImage: '/assets/game/scene2/evi1.png',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.flac',
    effect: null,
    characterImage: '/assets/game/scene2/evi1.png',
    questionId: 5,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.flac',
    effect: null,
    characterImage: '/assets/game/scene2/evi1.png',
    questionId: 6,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.flac',
    effect: null,
    characterImage: '/assets/game/scene2/evi1.png',
    questionId: 7,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.flac',
    effect: null,
    characterImage: '/assets/game/scene2/evi1.png',
    questionId: 8,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.flac',
    effect: null,
    characterImage: '/assets/game/scene2/evi1.png',
    questionId: 9,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.flac',
    effect: null,
    characterImage: '/assets/game/scene2/evi1.png',
    questionId: 10,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/frame2.png',
    audio: '/assets/game/scene2/audio2.flac',
    effect: null,
    characterImage: '/assets/game/scene2/evi1.png',
    questionId: 11,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene2/frame3.gif',
    audio: '/assets/game/scene2/audio2.flac',
    text: 'VIRUS: (Transisi tiba-tiba, layar berkedip merah)',
    effect: 'neon',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene2/frame3.gif',
    audio: '/assets/game/scene2/audio2.flac',
    text: 'Virus level 2 menyerang. Kamu harus mempertahankan 3 titik data sebelum rusak total.',
    effect: null,
    questionId: null,
    autoPlay: true,
    redirectToTowerGames: true,
    waves: 2,
  },
]; 