// Sebelum scene1Dialog dijalankan, pastikan user sudah mengisi nama dan lokasi di UI
export const scene1Dialog = [
  {
    image: '/assets/game/scene1/frame1.png',
    audio: '/assets/game/scene1/audio1.mp3',
    text: 'Apa yang terjadi di sini?',
    effect: null,
    questionId: null,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.mp3',
    text: 'Komputer ini tiba-tiba menyala sendiri...',
    questionId: null,
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame3.png',
    audio: '/assets/game/scene1/audio1.mp3',
    text: 'E.V.I. : identifikasi Pengguna ',
    effect: 'blink-shake',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.mp3',
    text: 'E.V.I.: Selamat datang, manusia.',
    effect: 'blink-shake',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.mp3',
    text: 'E.V.I.: Aku membutuhkan bantuanmu.',
    effect: 'blink-shake',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.mp3',
    text: 'E.V.I.: Sebelum itu, aku ingin tahu tentangmu.',
    effect: 'blink-shake',
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.mp3',
    effect: 'blink-shake',
    questionId: 1, 
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.mp3',
    effect: 'blink-shake',
    questionId: 2, 
    autoPlay: false,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.mp3',
    text: 'E.V.I.: Terima kasih atas jawabannya.',
    effect: 'blink-shake',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene1/frame2.png',
    audio: '/assets/game/scene1/audio1.mp3',
    text: 'E.V.I.: Sekarang, mari kita mulai.',
    effect: 'blink-shake',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene1/berguncang1.gif',
    audio: '/assets/game/scene1/audio1.mp3',
    text: 'Komputer mulai bergetar hebat...',
    effect: 'shake',
    questionId: null,
    autoPlay: true,
  },
  {
    image: '/assets/game/scene1/berguncang2.gif',
    audio: '/assets/game/scene1/audio1.mp3',
    text: 'VIRUS muncul di layar!',
    effect: 'neon',
    questionId: null,
    autoPlay: true,
    redirectToTowerGames: true,
    waves: 1,
  }
 ]; 